version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:8080"
    networks:
      - app-tier
  db:
    image: supabase/postgres:15.14.1.003
    container_name: supabase-postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-tier

  redis:
    image: redis:latest
    container_name: salang-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-tier

volumes:
  postgres-data:
    driver: local

networks:
  app-tier:
    driver: bridge