# application-dev.yml (개발용 설정)
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

# S3 Configuration
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucketName: ${AWS_S3_BUCKET_NAME}
    region:
      static: ${AWS_REGION}
    stack:
      auto: ${AWS_STACK_AUTO}