name: ⚙️ CI-Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ setting/SL-29 ]
jobs:
  ci:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: ${{ secrets.SPRING_DATASOURCE_TEST_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: salang
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin' 

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-

    - name: Print environment variables for debugging # 디버깅 단계 추가
      run: echo "Test DB password is ${{ secrets.POSTGRES_PASSWORD }}"

    - name: Build and Run Tests
      run: ./gradlew clean test --no-daemon
      env:
        SPRING_DATASOURCE_TEST_URL: ${{ secrets.SPRING_DATASOURCE_TEST_URL }}
        SPRING_DATASOURCE_TEST_USERNAME: ${{ secrets.SPRING_DATASOURCE_TEST_USERNAME }}
        SPRING_DATASOURCE_TEST_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}