name: ⚙️ CI-Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ setting/SL-29 ]
jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: salang
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin' 

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-

    - name: Download wait-for-it.sh
      run: |
        curl -sSLo wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
        chmod +x wait-for-it.sh

    - name: Wait for PostgreSQL
      run: ./wait-for-it.sh postgres:5432 --timeout=60 --strict -- echo "PostgreSQL is up"

    - name: Build and Run Tests
      run: ./gradlew clean test --no-daemon
      env:
        SPRING_DATASOURCE_TEST_URL: jdbc:postgresql://postgres:5432/salang
        SPRING_DATASOURCE_TEST_USERNAME: postgres
        SPRING_DATASOURCE_TEST_PASSWORD: password